name = "yeaarc"
main = "src/worker.js"
compatibility_date = "2026-07-18"
workers_dev = true

[[kv_namespaces]]
binding = "LEADERBOARD"
id = "2688df6e2db84ba6bf9e9853bfc7a0c0"
preview_id = "efac8969b5ce4986965d650361cade29"

[assets]
directory = "./dist"
binding = "ASSETS"
html_handling = "none"
not_found_handling = "404-page"
